version: "3.9"

services:
  panel-backend:
    container_name: panel-backend
    build:
      context: ./Panel
      dockerfile: Dockerfile.backend
    env_file:
      - ./Panel/.env
      - ./Panel/.env.local
    environment:
      - PORT=9000
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=9000
    ports:
      - "9000:9000"
    restart: unless-stopped

  panel-frontend:
    container_name: panel-frontend
    build:
      context: ./Panel
      dockerfile: Dockerfile.frontend
    depends_on:
      - panel-backend
    environment:
      # Build does not need backend URL if Nginx proxies /api to backend
      - NGINX_BACKEND=http://panel-backend:9000
    ports:
      - "5175:80"
    restart: unless-stopped

networks:
  default:
    name: panel-network
    driver: bridge
