
nixPkgs = [
	'nodejs_20',
	'npm-9_x',
	'curl',
	'wget'
]
nixPkgs = [
	'nodejs_20',
	'npm-9_x',
	'curl',
	'wget'
]


[install]
cmds = ["cd Panel && npm ci"]


[build]
cmds = ["cd Panel && npm run build"]


[start]
cmd = "cd Panel && npm run preview -- --port $PORT --host 0.0.0.0"
