name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Verify frontend build
        working-directory: Panel
        run: |
          npm ci
          npm run build
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install backend deps
        working-directory: Panel
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Docker build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: avukat-bilgi-sistemi:test
